#!/usr/bin/env python3
"""
19_export.py — make the corpus PORTABLE by folding every JSON index into the one SQLite DB,
so `index/pca_minutes.db` is a SELF-CONTAINED, queryable artifact needing no scripts/Python.

Already in the DB (from 05/08): pages(+pages_fts), sections(+sections_fts), cases(+cases_fts).
This adds, idempotently (drop+recreate), the layers that were JSON-only:
  structure   — the document hierarchy (PART > session/appendix > section/grouping > overture),
                flattened with parent_id so you can ask "what section is page X in".
  overtures   — the proposal catalogue (number, source, page, enclosing context).
  sjc_roster  — the official SJC case roster (ground-truth docket numbers/titles).
  bco_changes / bco_renumberings / citation_corrections — the BCO concordance layer.

Run AFTER the pipeline (…07/09/08). Re-runnable.  CLI: `19_export.py`  (writes into pca_minutes.db)
"""
from __future__ import annotations
import glob, json, os, sqlite3

ROOT = "/workspace"
DB = os.path.join(ROOT, "index", "pca_minutes.db")
IDX = os.path.join(ROOT, "index")


def _table(c, name, cols, rows):
    c.execute(f"DROP TABLE IF EXISTS {name}")
    c.execute(f"CREATE TABLE {name} ({', '.join(cols)})")
    if rows:
        ph = ",".join("?" * len(rows[0]))
        c.executemany(f"INSERT INTO {name} VALUES ({ph})", rows)
    return len(rows)


def _jsonl(path):
    return [json.loads(l) for l in open(path)] if os.path.exists(path) else []


def main():
    c = sqlite3.connect(DB)

    # overture subject titles (generated by 21 + LLM), keyed (vol, number, pdf_page)
    titles = {}
    tp = os.path.join(IDX, "overture_titles.jsonl")
    if os.path.exists(tp):
        for d in _jsonl(tp):
            titles[(d["vol"], d["number"], d.get("pdf_page"))] = d["title"]
    # overture dispositions + final (cross-GA ratification) disposition, keyed (vol, number)
    disp = {}
    dp = os.path.join(IDX, "overture_dispositions.jsonl")
    if os.path.exists(dp):
        for d in _jsonl(dp):
            disp[(d["vol"], d["number"], d.get("pdf_page"))] = d

    # 1) structure: flatten each volume's tree into nodes with parent linkage + a sequence order
    struct_rows, ov_rows = [], []
    nid = 0
    for p in sorted(glob.glob(os.path.join(IDX, "structure", "ga*.json"))):
        t = json.load(open(p))
        vol, ordn, year = t["volume"], t["ga_ordinal"], t["year"]
        seq = [0]

        def walk(node, parent):
            nonlocal nid
            nid += 1
            me = nid
            struct_rows.append((me, vol, ordn, year, parent, node.get("type"),
                                node.get("label"), node.get("title"),
                                node.get("number"), node.get("source"),
                                node.get("pdf_page"), node.get("printed_page"), seq[0]))
            seq[0] += 1
            for ch in node.get("children", []):
                walk(ch, me)
        for part in t["parts"]:
            walk(part, None)
        for o in t.get("overtures", []):
            pages = o.get("pages") or [o["pdf_page"]]
            title = next((titles[(vol, o["number"], p)] for p in pages
                          if (vol, o["number"], p) in titles), None)
            dd = disp.get((vol, o["number"], o["pdf_page"]), {})
            ov_rows.append((vol, ordn, year, o["number"], o["source"],
                            o["pdf_page"], o.get("printed_page"), o.get("in"), title,
                            ";".join(str(p) for p in pages),
                            dd.get("disposition"), dd.get("final_disposition"),
                            dd.get("ratification_note")))

    n_s = _table(c, "structure",
                 ["node_id INTEGER PRIMARY KEY", "vol TEXT", "ga_ordinal INT", "year INT",
                  "parent_id INT", "type TEXT", "label TEXT", "title TEXT", "number INT",
                  "source TEXT", "pdf_page INT", "printed_page INT", "seq INT"], struct_rows)
    n_o = _table(c, "overtures",
                 ["vol TEXT", "ga_ordinal INT", "year INT", "number INT", "source TEXT",
                  "pdf_page INT", "printed_page INT", "context TEXT", "title TEXT", "pages TEXT",
                  "disposition TEXT", "final_disposition TEXT", "ratification_note TEXT"], ov_rows)
    c.execute("CREATE INDEX IF NOT EXISTS ix_structure_page ON structure(vol, pdf_page)")
    c.execute("CREATE INDEX IF NOT EXISTS ix_structure_type ON structure(type)")
    c.execute("CREATE INDEX IF NOT EXISTS ix_overtures_ga ON overtures(ga_ordinal)")

    # 2) auxiliary constitutional layers (kept as JSON-text rows so any schema drift is preserved)
    def load_jsonl_table(name, path, cols, pick):
        rows = [tuple(pick(d)) for d in _jsonl(path)]
        return _table(c, name, cols, rows)

    n_r = load_jsonl_table(
        "sjc_roster", os.path.join(IDX, "sjc_official", "roster.jsonl"),
        ["canonical_number TEXT", "title TEXT", "pdf_url TEXT", "raw TEXT"],
        lambda d: (d.get("canonical_number"), d.get("title"),
                   d.get("official_pdf_url") or d.get("pdf_url"), json.dumps(d, ensure_ascii=False)))
    n_bc = load_jsonl_table(
        "bco_changes", os.path.join(IDX, "bco_changes.jsonl"),
        ["year INT", "raw TEXT"], lambda d: (d.get("year"), json.dumps(d, ensure_ascii=False)))
    n_br = load_jsonl_table(
        "bco_renumberings", os.path.join(IDX, "bco_renumberings.jsonl"),
        ["raw TEXT"], lambda d: (json.dumps(d, ensure_ascii=False),))
    n_cc = load_jsonl_table(
        "citation_corrections", os.path.join(IDX, "citation_corrections.jsonl"),
        ["raw TEXT"], lambda d: (json.dumps(d, ensure_ascii=False),))

    c.execute("INSERT OR REPLACE INTO meta VALUES ('portable_export', ?)",
              (json.dumps({"structure": n_s, "overtures": n_o, "sjc_roster": n_r,
                           "bco_changes": n_bc, "bco_renumberings": n_br,
                           "citation_corrections": n_cc}),)) if _has_meta(c) else None
    c.commit()
    print(f"folded into {DB}:  structure={n_s}  overtures={n_o}  sjc_roster={n_r} "
          f" bco_changes={n_bc}  bco_renumberings={n_br}  citation_corrections={n_cc}")
    c.close()


def _has_meta(c):
    return bool(c.execute("SELECT 1 FROM sqlite_master WHERE type='table' AND name='meta'").fetchone())


if __name__ == "__main__":
    main()
